package klondike.models;

public enum Options {
	MOVE_DECK_TO_DISCARDS,
	MOVE_DISCARD_TO_DECK,
	MOVE_DISCARD_TO_STAIR,
	MOVE_DISCARD_TO_SUIT,
	MOVE_STAIR_TO_SUIT,
	MOVE_STAIR_TO_STAIR,
	MOVE_SUIT_TO_STAIR,
	SHOW_STAIR_CARD,
	EXIT;
}
